name: Deploy AI Service to AWS ECS

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: ai-insights-service
  ECS_CLUSTER: ai-insights-cluster
  ECS_SERVICE: ai-insights-service
  ECS_TASK_DEFINITION_FAMILY: ai-insights-service-task
  CONTAINER_NAME: ai-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Checkout Code ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Step 2: Configure AWS Credentials with OIDC ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # --- Step 3: Login to Amazon ECR ---
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- Step 4: Build and Push Docker Image ---
      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}-${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:cache
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:cache,mode=max

      # --- Step 5: Download Latest Task Definition ---
      - name: Get latest task definition
        id: task-def
        run: |
          aws ecs describe-task-definition \
            --task-definition $ECS_TASK_DEFINITION_FAMILY \
            --query taskDefinition > task-definition.json
          echo "task-def=task-definition.json" >> $GITHUB_OUTPUT

      # --- Step 6: Determine image URI ---
      - name: Set image URI
        id: image-uri
        run: |
          if [ -n "${{ steps.build-image.outputs.digest }}" ]; then
            echo "uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}@${{ steps.build-image.outputs.digest }}" >> $GITHUB_OUTPUT
          else
            echo "uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      # --- Step 7: Render New Task Definition ---
      - name: Render new task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-def }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.image-uri.outputs.uri }}
